language: python
dist: trusty
sudo: required
python:
    - "2.7"
services:
    - docker
postgresql: "9.1"
install:
    - pip install coveralls
script:
    - bash bin/travis-build.bash
    - pylint ckanext/
